DBookmark/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

import bookmark
from bookmark.views import BookmarkListView

urlpatterns = [
    # path('', BookmarkListView.as_view(), name='home'),
    path('', bookmark.views.list_bookmark, name='home'),
    path('bookmark/', include('bookmark.urls')),
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path

from accounts import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.register, name='register'), #accounts:register
    path('login/', views.my_login, name='login'),
    path('logout/', views.my_logout, name='logout'),
]

bookmark/urls.py
from django.urls import path

from bookmark import views
from bookmark.views import BookmarkListView, BookmarkCreateView, BookmarkDetailView, BookmarkUpdateView, \
    BookmarkDeleteView

app_name = 'bookmark'

urlpatterns = [
    # path('list/', BookmarkListView.as_view(), name='list'),  # bookmark:list
    path('list2/', views.list_bookmark, name='list'),
    # path('add/', BookmarkCreateView.as_view(), name='add'),  # bookmark:add
    path('add2/', views.create_bookmark, name='add'),  # bookmark:add
    # path('detail/<int:pk>/', BookmarkDetailView.as_view(), name='detail'),  #bookmark:detail
    path('detail2/<int:pk>/', views.detail_bookmark, name='detail'),  #bookmark:detail
    # path('edit/<int:pk>/', BookmarkUpdateView.as_view(), name='edit'),  #bookmark:edit
    path('edit2/<int:pk>/', views.modify_bookmark, name='edit'),  #bookmark:edit
    # path('delete/<int:pk>/', BookmarkDeleteView.as_view(), name='delete'),  #bookmark:delete
    path('delete2/<int:pk>/', views.delete_bookmark, name='delete'),  #bookmark:delete
]

bookmark/models.py
from django.db import models
from django.shortcuts import resolve_url

from accounts.models import Profile


class Bookmark(models.Model):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=10)
    url = models.URLField()

    def __str__(self):
        return f'{self.name} : {self.url}'    #어무해 : http://bit.ly/2022NP

    def get_absolute_url(self):
        return resolve_url('bookmark:detail', pk=self.pk)

bookmark/forms.py
from django import forms

from bookmark.models import Bookmark


class BookmarkCreationForm(forms.ModelForm):
    url = forms.CharField(label='링크', widget=forms.TextInput)

    class Meta:
        model = Bookmark
        fields = ['name', 'url']

    def clean_url(self):
        url = self.cleaned_data.get('url')  # url 가져오자
        if not (url.startswith('http://') or url.startswith('https://')):  # 만약 http:// 나 https://가 없으면,
            url = 'https://' + url  # https:// 추가하자
        return url

    def save(self, commit=True):
        new_bookmark = Bookmark.objects.create(
            name=self.cleaned_data.get('name'),  # 사용자가 입력한 내용을 clean_name()하고 깨끗해진 것 가져오자
            url=self.cleaned_data.get('url'),  # 사용자가 입력한 내용을 clean_url()하고 깨끗해진 것 가져오자
        )
        return new_bookmark


class BookmarkChangeForm(forms.ModelForm):
    class Meta:
        model = Bookmark
        fields = ['name', 'url']

bookmark/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView

from accounts.models import Profile
from bookmark.forms import BookmarkCreationForm, BookmarkChangeForm
from bookmark.models import Bookmark


class BookmarkListView(ListView):
    model = Bookmark

    # bookmark_list.html, {'bookmark_list': Bookmark.objects.all()}

    def get_queryset(self):
        user = self.request.user
        if user.is_authenticated:  # 로그인 하면, 로그인한 사용자의 북마크만 보이자
            # user -> profile -> bookmark_list
            profile = Profile.objects.get(user=user)  # user -> profile
            bookmark_list = Bookmark.objects.filter(profile=profile)  # profile -> bookmark_list
        else:  # 로그인 안하면,
            # bookmark_list = Bookmark.objects.all()    #북마크 다 보여주자
            bookmark_list = Bookmark.objects.none()  # 북마크 보이지 말자
        return bookmark_list


class BookmarkCreateView(LoginRequiredMixin, CreateView):
    model = Bookmark
    fields = ['profile', 'name', 'url']  # '__all__'
    template_name_suffix = '_create'  # bookmark_form.html -> bookmark_create.html
    success_url = reverse_lazy('bookmark:list')

    def get_initial(self):
        # user -> profile
        user = self.request.user
        profile = Profile.objects.get(user=user)
        return {'profile': profile}


class BookmarkDetailView(LoginRequiredMixin, DetailView):
    model = Bookmark


class BookmarkUpdateView(LoginRequiredMixin, UpdateView):
    model = Bookmark
    fields = ['name', 'url']  # '__all__'
    template_name_suffix = '_update'  # bookmark_update.html
    # success_url = reverse_lazy('bookmark:list')   #success_url 없으면 model의 get_absolute_url() 호출


class BookmarkDeleteView(LoginRequiredMixin, DeleteView):
    model = Bookmark
    success_url = reverse_lazy('bookmark:list')


def list_bookmark(request):
    # 로그인 사용자 확인하자
    user = request.user
    if user.is_authenticated:  # 로그인 되어있으면
        profile = Profile.objects.get(user=user)
        bookmark_list = Bookmark.objects.filter(profile=profile)  # 그 사용자의 북마크 가져오자
    else:  # 로그인 안되어 있으면
        bookmark_list = Bookmark.objects.none()  # 북마크 없는것 가져오자

    return render(request, 'bookmark/bookmark_list.html', {'bookmark_list': bookmark_list})


def detail_bookmark(request, pk):
    bookmark = Bookmark.objects.get(pk=pk)
    return render(request, 'bookmark/bookmark_detail.html', {'bookmark': bookmark})


@login_required
def delete_bookmark(request, pk):
    if request.method == 'POST':  # 삭제 버튼 눌렀을 때
        bookmark = Bookmark.objects.get(pk=pk)
        bookmark.delete()  # DELETE FROM table WHERE 조건
        return redirect('bookmark:list')
    else:  # 처음 bookmark_delete.html 요청
        bookmark = Bookmark.objects.get(pk=pk)
        return render(request, 'bookmark/bookmark_confirm_delete.html', {'bookmark': bookmark})


@login_required
def create_bookmark(request):
    if request.method == 'POST':  # 사용자가 입력하고 버튼 눌렀을 때
        form = BookmarkCreationForm(request.POST)  # form 가져오자
        if form.is_valid():  # is_valid()
            new_bookmark = form.save(commit=False)  # new_bookmark 생성하자(name, url)
            new_bookmark.profile = Profile.objects.get(user=request.user)  # new_bookmark에 profile 추가하자
            new_bookmark.save()
            return redirect('bookmark:list')  # bookmark:list 이동하자
    else:  # 빈 폼
        form = BookmarkCreationForm()
    return render(request, 'bookmark/bookmark_create.html', {'form': form})


@login_required
def modify_bookmark(request, pk):
    if request.method == 'POST':
        form = BookmarkChangeForm(request.POST)  # form 가져오자
        if form.is_valid():  # is_valid()
            bookmark = Bookmark.objects.get(pk=pk)  # pk에 해당하는 bookmark 가져오자
            bookmark.name = form.cleaned_data.get('name')  # 사용자가 입력한 name set
            bookmark.url = form.cleaned_data.get('url')  # 사용자가 입력한 url set
            bookmark.save()
            return redirect('bookmark:list')  # bookmark:list로 이동하자
    else:
        bookmark = Bookmark.objects.get(pk=pk)  # pk에 해당하는 bookmark 정보 가져오자
        form = BookmarkChangeForm(instance=bookmark)  # bookmark 정보 넣은 form
    return render(request, 'bookmark/bookmark_update.html', {'form': form})

bookmark/templates/bookmark/bookmark_confirm_delete.html
{% extends 'base.html' %}

{% block title %}delete Bookmark{% endblock %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    <div class="alert alert-danger">
        너 북마크 {{ bookmark }} 진짜 지울거야?
    </div>
    <input type="submit" value="진짜 삭제" class="btn btn-danger">
    <input type="button" value="지우지마" onclick="history.back();" class="btn btn-light">
</form>
{% endblock %}

bookmark/templates/bookmark/bookmark_create.html
{% extends 'base.html' %}

{% block title %}Add Bookmark{% endblock %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    {{ form.profile.as_hidden }}
    <p>{{ form.name.label_tag }} {{ form.name }}</p>
    <p>{{ form.url.label_tag }} {{ form.url }}</p>
    <input type="submit" value="Add" class="btn btn-success">
</form>
{% endblock %}

bookmark/templates/bookmark/bookmark_detail.html
{% extends 'base.html' %}

{% block title %}Bookmark Detail{% endblock %}

{% block content %}
<h1>{{ bookmark.name }}</h1>
<a href="{{ bookmark.url }}">{{ bookmark.url }}</a>
<a href="{% url 'bookmark:list' %}" class="btn btn-warning">Go to Bookmark List</a>
{% endblock %}

bookmark/templates/bookmark/bookmark_list.html
{% extends 'base.html' %}

{% block title %}Bookmark List{% endblock %}

{% block content %}
<div class="btn-group">
    {% if user.is_authenticated %}
        <a href="{% url 'bookmark:add' %}" class="btn btn-success">Add Bookmark</a>
        <a href="{% url 'accounts:logout' %}" class="btn btn-light">logout</a>
    {% else %}
        <a href="{% url 'accounts:register' %}" class="btn btn-warning">register</a>
        <a href="{% url 'accounts:login' %}" class="btn btn-info">login</a>
    {% endif %}
</div>
<table class="table">
    <thead>
    <tr>
        <th>#</th>
        <th>Name</th>
        <th>URL</th>
        <th>Edit</th>
        <th>Delete</th>
    </tr>
    </thead>
    <tbody>
    {% for bookmark in bookmark_list %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td><a href="{% url 'bookmark:detail' pk=bookmark.pk %}">{{ bookmark.name }}</a></td>
            <td><a href="{{ bookmark.url }}">{{ bookmark.url }}</a></td>
            <td><a href="{% url 'bookmark:edit' pk=bookmark.pk %}" class="btn btn-primary btn-sm">Edit</a></td>
            <td><a href="{% url 'bookmark:delete' pk=bookmark.pk %}" class="btn btn-danger btn-sm">Delete</a></td>
        </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}

bookmark/templates/bookmark/bookmark_update.html
{% extends 'base.html' %}

{% block title %}edit Bookmark{% endblock %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_ul }}
    <input type="submit" value="Edit" class="btn btn-primary">
</form>
{% endblock %}